- type: autoSalaryConfig
  id: AutoSalaryConfig
  payInterval: 1200

- type: autoSalaryJob
  id: Sheriff
  localizedName: Шериф
  salary: 17000

- type: autoSalaryJob
  id: FrontierRepresentative
  localizedName: Представитель Фронтира
  salary: 20000

- type: autoSalaryJob
  id: OutpostDispatcher
  localizedName: Диспетчер Аванпоста
  salary: 13500

- type: autoSalaryJob
  id: MailCarrier
  localizedName: Почтальон
  salary: 8000

- type: autoSalaryJob
  id: AFOfficer
  localizedName: Офицер АФ
  salary: 11000

- type: autoSalaryJob
  id: Bailiff
  localizedName: Бейлиф
  salary: 13500

- type: autoSalaryJob
  id: Lieutenant
  localizedName: Лейтенант
  salary: 12000

- type: autoSalaryJob
  id: Ranger
  localizedName: Рейнджер
  salary: 10000

- type: autoSalaryJob
  id: Coroner
  localizedName: Коронер
  salary: 11000

- type: autoSalaryJob
  id: Detective
  localizedName: Детектив
  salary: 11000

- type: autoSalaryJob
  id: LegalRepresentative
  localizedName: Представитель ЮД
  salary: 15000

- type: autoSalaryJob
  id: Cadet
  localizedName: Кадет
  salary: 8000

- type: autoSalaryJob
  id: Paramedic
  localizedName: Парамедик
  salary: 10000

- type: autoSalaryJob
  id: MedicalOperationsManager
  localizedName: Менеджер медицинских операций
  salary: 12000

- type: autoSalaryJob
  id: AFEngineer
  localizedName: Инженер АФ
  salary: 9000

- type: autoSalaryJob
  id: AFDoctor
  localizedName: Врач АФ
  salary: 9000

- type: autoSalaryJob
  id: AFWorker
  localizedName: Работник АФ
  salary: 9000
